spring:
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:memdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
  jpa:
    database: h2
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      max-file-size: 10Mb
recordings:
  security:
    aws-access-key-id: ${AWS_ACCESS_KEY_ID}
    aws-secret-key: ${AWS_SECRET_KEY}