CREATE SEQUENCE RECORDINGS_SEQ;
CREATE TABLE RECORDINGS
(
  ID          BIGINT      NOT NULL PRIMARY KEY,
  USER_ID     BIGINT      NOT NULL REFERENCES USERS (ID),
  TITLE       VARCHAR(64),
  UPLOAD_TIME TIMESTAMP   NOT NULL,
  DURATION    BIGINT      NOT NULL,
  FILE_NAME   VARCHAR(32) NOT NULL
);

