CREATE SEQUENCE PERMISSIONS_SEQ;
CREATE TABLE PERMISSIONS
(
  ID           BIGINT NOT NULL PRIMARY KEY,
  USER_ID      BIGINT NOT NULL REFERENCES USERS (ID),
  RECORDING_ID BIGINT NOT NULL REFERENCES RECORDINGS (ID)
);
