CREATE SEQUENCE MARKS_SEQ;
CREATE TABLE MARKS
(
  ID           BIGINT      NOT NULL PRIMARY KEY,
  USER_ID      BIGINT      NOT NULL REFERENCES USERS (ID),
  RECORDING_ID BIGINT      NOT NULL REFERENCES RECORDINGS (ID),
  NAME         VARCHAR(64) NOT NULL,
  MARK_TIME    BIGINT      NOT NULL
);
