CREATE SEQUENCE COMMENTS_SEQ;
CREATE TABLE COMMENTS
(
  ID           BIGINT        NOT NULL PRIMARY KEY,
  USER_ID      BIGINT        NOT NULL REFERENCES USERS (ID),
  MARK_ID      BIGINT        NOT NULL REFERENCES MARKS (ID),
  COMMENT      VARCHAR(1000) NOT NULL,
  COMMENT_TIME TIMESTAMP     NOT NULL
);
